spring:
  profiles:
    active: local
    
  jpa:
    properties:
      hibernate:
        format-sql: 'true'
        show-sql: 'true '
    hibernate:
      ddl-auto: none # DB 테이블생성 시 create [DROP and CREATE] 또는 update [CREATE], 완료 후 none
    open-in-view: 'false'
  mvc:
    static-path-pattern: /resources/**
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  main:
    allow-bean-definition-overriding: 'true'      
  devtools:
    livereload:
      enabled: 'true' 
    
server:
  port: '8070'
  servlet:
    context-path: /
    session: 
      timeout: 7200 #2시간
  error:
    include-message: always
    include-exception: true
    include-stacktrace: never
          
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info
            
---
spring:
  config.activate.on-profile: dev 
  
  datasource:
    password: post
    username: post
    url: jdbc:log4jdbc:postgresql://localhost:5432/dashBoard?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: '12'
      
---
spring:
  config.activate.on-profile: local 
  
  datasource:
    password: post
    username: post
    url: jdbc:log4jdbc:postgresql://localhost:5432/dashBoard?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: '12'